### ISSUE TITLE
GitHub Action should fail if pushing diagram to GH fails

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [githubocto/repo-visualizer#2]
In my case pushing diagram failed because `master` branch is protected - however, the GH Action had success status, and I was a bit confused for a moment why I don't see a diagram in the repo ;-)

https://github.com/fsharp/FsAutoComplete/runs/3253469374?check_suite_focus=true#step:3:281

**Comment by sobolevn** [comment]
The same for me:

<img width="1260" alt="Снимок экрана 2021-08-05 в 19 33 19" src="https://user-images.githubusercontent.com/4660275/128387283-3ecfb169-2f22-4952-9317-1adef92eff4a.png">


```
 [master 39967ca] Repo visualizer: updated diagram
 1 file changed, 1 insertion(+)
 create mode 100644 docs/diagram.svg
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: At least 1 approving review is required by reviewers with write access.        
To https://github.com/wemake-services/wemake-python-styleguide
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/wemake-services/wemake-python-styleguide'
(node:1671) UnhandledPromiseRejectionWarning: Error: The process '/usr/bin/git' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/githubocto/repo-visualizer/main/index.js:935:21)
    at ExecState.CheckComplete (/home/runner/work/_actions/githubocto/repo-visualizer/main/index.js:921:16)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/githubocto/repo-visualizer/main/index.js:824:21)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
(node:1671) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1671) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Wattenberger** [comment]
thanks for the issue! closing with #9
